name: Update Iniciativa Metal Gear feed

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      - name: Run update_imetal
        run: python scripts/update_imetal.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/*/feed.xml
          git commit -m "Update Iniciativa Metal Gear feed" || echo "No changes"
          git push