name: Refresh Podcast Feeds

on:
  workflow_dispatch:  # Solo ejecución manual

jobs:
  refresh-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Refresh feeds
        run: python scripts/refresh_podcast_feeds.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No hay cambios en los feeds."
          else
            git commit -m "Refresh feed.xml from feed0.xml"
            git push
          fi