name: Update imagen feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          pip install -r requirements.txt || true

      - name: Update imagen feeds
        run: |
          python3 update_feeds.py imagen.txt

      - name: Commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Update imagen feeds" || echo "No changes to commit"
          git push