name: antiguo alotroladodelmicrofono

on:
  workflow_dispatch:   # solo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update_imagen
        run: python scripts/update_imagen.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public
          git commit -m "update_imagen: feeds updated with om:sec and description changes" || echo "No changes"

          git push




